### ISSUE TITLE
Specific MP3 types?

### ISSUE THREAD

**Issue by dy** [hemanth/is-mp3#17]
Hi @hemanth!

Take example https://ia802508.us.archive.org/5/items/testmp3testfile/mpthreetest.mp3.
This file, downloaded as buffer, is not detected by the package properly.
Related to https://github.com/audiojs/audio-loader/issues/13 and https://github.com/audiojs/audio-loader/pull/14

**Comment by hemanth** [comment]
Thanks, just published `v1.1.3`  🎉
